"""add front_back_paths

Revision ID: 232fd1c975ea
Revises: 51d4dc079555
Create Date: 2025-06-07 22:58:55.896361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232fd1c975ea'
down_revision = '51d4dc079555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('back_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('back_path')
        batch_op.drop_column('front_path')

    # ### end Alembic commands ###
